const users = [
  {
    id: 2,
    name: "Adrian @asf",
    active: true,
    matches: [4],
    reasons: ["Sport"],
    interests: [],
    description: "Lorem ipsum",
    coffeePoints: 3,
    gossipPoints: 1,
    gamePoints: 0,
    image: "https://clacksnack.clacks.de/conterior/gallery/employees/56/1569396965_43261.jpg",
    fakeImage: "https://i.pinimg.com/564x/a7/71/26/a77126ed93bff8d24aaa4aa44c77a9b8.jpg",
  },
  {
    id: 3,
    name: "Anne @ah",
    active: true,
    matches: [1, 2],
    reasons: ["Sport"],
    interests: ["Füßball", "Laufen gehen"],
    description: "Lorem ipsum",
    coffeePoints: 2,
    gossipPoints: 1,
    gamePoints: 0,
    image: "https://clacksnack.clacks.de/conterior/gallery/employees/15/1598895431_12325.jpg",
    fakeImage: "https://i.pinimg.com/736x/52/bc/39/52bc3928fd63daa22ebfb555f9ae07dd.jpg",
  },
  {
    id: 4,
    name: "Annika @ann",
    active: false,
    matches: [1, 3],
    reasons: ["Sport"],
    interests: ["Gymnastik", "Füßball", "Laufen gehen"],
    description: "Lorem ipsum",
    coffeePoints: 5,
    gossipPoints: 4,
    gamePoints: 0,
    image: "https://clacksnack.clacks.de/conterior/gallery/employees/97/1569397161_19623.jpg",
    fakeImage: "https://i1.wp.com/katzenworld.co.uk/wp-content/uploads/2019/06/funny-cat.jpeg?fit=1920%2C1920&ssl=1",
  },
  {
    id: 5,
    name: "Thomas @tk",
    active: true,
    matches: [4],
    reasons: ["Sport"],
    interests: ["Zumba", "Yoga"],
    description: "Lorem ipsum",
    coffeePoints: 3,
    gossipPoints: 1,
    gamePoints: 10,
    image: "https://clacksnack.clacks.de/conterior/gallery/employees/28/thomas_kohler_blau.jpg",
    fakeImage: "https://i.chzbgr.com/full/9112752128/h94C6655E/cute-cat-looking-at-the-camera-with-its-ears-hiding",
  },
  {
    id: 6,
    name: "Carolina @cm",
    active: true,
    matches: [1, 2],
    reasons: ["Sport"],
    interests: ["Zumba", "Yoga", "Gymnastik"],
    description: "Lorem ipsum",
    coffeePoints: 7,
    gossipPoints: 0,
    gamePoints: 50,
    image: "https://clacksnack.clacks.de/conterior/gallery/employees/311812/1591168849_71557.png",
    fakeImage: "https://static.onecms.io/wp-content/uploads/sites/23/2015/06/17/gettyimages-521187729-1.jpg",
  },
  {
    id: 7,
    name: "Holger @hb",
    active: true,
    matches: [1, 2],
    reasons: ["Kaffee trinken"],
    interests: ["Mood", "Bier", "Bugs"],
    description: "Lorem ipsum",
    coffeePoints: 7,
    gossipPoints: 0,
    gamePoints: 50,
    image: "https://clacksnack.clacks.de/conterior/gallery/employees/2/1598035541_44487.jpg",
    fakeImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSwKK8tK-bcO1CgKAsnnyKVjf8Mx4AYF9Mqew&usqp=CAU",
  },
  {
    id: 8,
    name: "Olena @os",
    active: true,
    matches: [1, 4, 3],
    reasons: ["Kaffee trinken"],
    interests: ["Mood", "Bier"],
    description: "Lorem ipsum",
    coffeePoints: 7,
    gossipPoints: 0,
    gamePoints: 50,
    image: "https://clacksnack.clacks.de/conterior/gallery/employees/311819/1601023543_19280.jpg",
    fakeImage: "https://i.pinimg.com/736x/25/40/de/2540de1db897bbbc4972d348447f0bb8.jpg",
  },
];

export { users };
